[package]
name = "xtask"
edition = "2024"
version = "0.1.0"
build = "build.rs"

[dependencies]
anyhow = { workspace = true }
cargo_metadata = { workspace = true }
clap = { workspace = true, features = ["derive"] }
# 继承工作区的本地aya-ebpf依赖，无需单独指定git源
aya-ebpf = { workspace = true }
